default_stages: [commit]

repos:
  - repo: https://github.com/Trim21/pre-commit-hooks
    rev: 62dc921d5be199dd91853cdbe5be3e776f44ab4b  # frozen: v0.0.2
    hooks:
      - id: yamlfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: e1668fe86af3810fbca72b8653fe478e66a0afdc  # frozen: v3.2.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files  # check for file bigger than 500kb
      - id: debug-statements
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/timothycrosley/isort
    rev: 2e02c195afdb499be9068ca0d08c9d7d45912d4d  # frozen: 5.5.4
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: f766c29ec4bb6cf2674b81959871e59d5400380a  # frozen: v2.7.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/myint/autoflake
    rev: 7a53fdafc82c33f446915b60fcac947c51279260  # frozen: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/PyCQA/doc8.git
    rev: 1fc3c214b267d57188658c17b60cfed0752deb2f  # frozen: 0.9.0a1
    hooks:
      - id: doc8
        name: Check rst file
        args: [--max-line-length=88]
        files: \.rst$

  - repo: https://github.com/Trim21/poetry-check-lock.git
    rev: 63621580c70f106fd07748c262b6e08fef886ecc  # frozen: v0.0.3
    hooks:
      - id: poetry-check-lock

  - repo: https://github.com/psf/black
    rev: e66be67b9b6811913470f70c28b4d50f94d05b22  # frozen: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 86a6c50edae12eca8adbf9435e9e9edeb7e55bb0  # frozen: v2.4.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args:
          - --ignore=C0103,C0111,R0903,W503,W504,C812,C813,C815,C819,B008,E265,E501
          - --max-line-length=88
